### ISSUE TITLE
Sometimes, I do not have access to the exchange rate for fiat

### ISSUE THREAD

**Issue by Nogreedy** [Litecoin-Java/bitcoin-wallet#29]
This morning (and yesterday afternoon) I hadn't access to exchange rate and then I could'nt choose fiat currency. Only one fiat currency was available (dollar, but I'm not sure exchange rate $/LTC was updated correctly) and I couldn't choose euro (see screencapture below) ...

![sc20140113-151545](https://f.cloud.github.com/assets/6340683/1903856/8271abae-7c87-11e3-92d0-d6c09fd4660a.png)

Since 1 hour, it works : I have access to all foreign currencies and I can choose between €, $, ... (see below)

![sc20140113-194419](https://f.cloud.github.com/assets/6340683/1903938/88d37f4e-7c88-11e3-8f01-79cf9a78487e.png)

**Comment by hank** [comment]
Have you seen this happen recently?  I may add some more fiat exchange APIs for when the Yahoo! query fails...

**Comment by Nogreedy** [comment]
Now, it works perfectly, but yesterday it didn't work for a few hours...

**Comment by hank** [comment]
OK - it seems like your Yahoo! exchange API request is failing occasionally.  It would be good to have a backup for this anyway.  I found this:

https://blockchain.info/ticker

Since this has USD on it, we should be able to parse it into BigDecimal and get the fiat currency scaling factors (which is exactly what I'm doing with the Yahoo! API).  It wouldn't take too much code to add this.  I'm scheduling it for the next release and leaving it unassigned for now.

**Comment by adv0r** [comment]
I can try looking into that.

But simply reading the readme of the wallet, quote

https://github.com/adv0r/bitcoin-wallet/tree/messy/wallet

```
EXCHANGE RATES

Bitcoin Wallet reads this feed from "bitcoin charts" for getting exchange rates:

    http://bitcoincharts.com/t/weighted_prices.json

The feed is described on this page (see Weighted Prices):

    http://bitcoincharts.com/about/markets-api/

I chose this feed because it is not dependent on a single exchange. However, you should keep in
mind it's always a 24h average (falling back to 7d or even 30d if no trade occurred for a long
time).

If Bitcoincharts is not available, the feed from "Blockchain" is fetched instead:

    https://blockchain.info/ticker

The feed is described here:

    https://blockchain.info/api/exchange_rates_api
```

So its either the readme outdated or the issue is different.

There is an inner class into ExchangeRateProvider called YahooRatesProvider . Should I create a BlockchainRateProvider ? Or maybe should look deep into this issue and check against the documentation?

**Comment by hank** [comment]
This wallet is a fork - that readme was written for the original wallet.  You have the right idea with the BlockchainRateProvider, but you mentioned there might be some java libs around for doing these API calls so we don't have to do them ourselves - that's worth looking into as well.  Also, make it prefer Yahoo since there are more currencies, but fall back to blockchain.  Feel free to update the readme as well to reflect the current implementation.  Upstream changes can just be ignored for that readme file.

**Comment by Nogreedy** [comment]
Is it possible to use the well known BitcoinAverage?
https://bitcoinaverage.com/faq.htm
-enhancement scheduled : add LTC/BTC support on https://github.com/bitcoinaverage/bitcoinaverage/issues

Or perhaps : http://www.cryptocoincharts.info/v2/
http://www.cryptocoincharts.info/v2/tools/api

**Comment by hank** [comment]
That should work.  Maybe we can even make a preference

Nogreedy notifications@github.com wrote:

> Is it possible to use the well known BitcoinAverage?
> https://bitcoinaverage.com/faq.htm
> -enhancement scheduled : add LTC/BTC support on
> https://github.com/bitcoinaverage/bitcoinaverage/issues
> 
> Or perhaps : http://www.cryptocoincharts.info/v2/
> http://www.cryptocoincharts.info/v2/tools/api
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Litecoin-Java/bitcoin-wallet/issues/29#issuecomment-32697531

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Nogreedy** [comment]
version 3.30.2 (french version)
Now, I  haven't  access to the exchange rate for fiat.
The only fiat currency I can use is USD $.
I haven't access to the exchange rate since approximately 12 hours.
