### ISSUE TITLE
App is not available in german Play Store.

### ISSUE THREAD

**Issue by XenGi** [Litecoin-Java/bitcoin-wallet#36]
Please make the app available in the german play store so that I can download and update it automatically.

Btw, why are you using de.schildbach. as package name?

**Comment by hank** [comment]
It will be available very soon.  Because it contains encryption bytecode and has US contributions, it needed to go through export compliance.  I've read a lot about this, and I've determined that the TSU exception applies, just like it does in most Apache projects.

We may change the package name in the future with a refactor, but this was easy.  It would make more sense to move to a litecoin project package name.  Thanks for the suggestion.

**Comment by hank** [comment]
Published - should be there in short order.
