### ISSUE TITLE
Whats this project about?

### ISSUE THREAD

**Issue by UngarnFCP** [Litecoin-Java/bitcoin-wallet#62]
In the URL https://github.com/Litecoin-Java/bitcoin-wallet/issues/new
it looks like a bitcoin project.
In the Readme its called a Litecoin wallet.
- Is it bitcoin or litecoin?
- What is the difference to https://github.com/hank/litecoin-wallet if its a Litecoin Wallet?

**Comment by wtogami** [comment]
It's meant to eventually become a cleaner and better wallet that contributes code back to upstream bitcoin-wallet.  The underlying bitcoinj is named as such because it is meant to do both Bitcoin and Litecoin in the same library, not breaking Bitcoin compatibility and also submitting improvements upstream.  It currently is not capable of that due to ugly code that has to be cleaned up.
