### ISSUE TITLE
Can someone provide a screencast

### ISSUE THREAD

**Issue by UngarnFCP** [Litecoin-Java/bitcoin-wallet#63]
https://github.com/Litecoin-Java/bitcoin-wallet/wiki/Developer-HOWTO

"Set up litecoinJ Project"
Can someone provide a screencast here on how to setup Intellij? Some things are not clear. I downloaded IntelliJ and started it. Imported bitcoinj as a maven project. Added JDK and Android SDK and IntelliJ SDK. Do I need all 3 or just the JDK for bitcoinj? How do I create a maven build config that runs clean install? "Run" --> "Edit Configuration" --> and then?

**Comment by hank** [comment]
There aren't enough developers to warrant the time it would take to do a screencast.  For bitcoinj, you don't need Android because it's just a java project.  mvn clean install should work from the command line.  Just JDK is needed in IntelliJ.  Maven build tasks in Edit Configurations are under + -> Maven.  I have one that does clean install for instance.

**Comment by hank** [comment]
Also, in my developer howto, it says:

> After the project is created, create a maven build configuration that runs clean install.

And links to the official documentation on making that kind of build configuration.  The official docs for IntelliJ should be sufficient to get you set up.  If they are not, I would post a general question on stackoverflow.
